version: '3'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: 'python manage.py migrate && python manage.py makemigrations && python3 manage.py runserver 0.0.0.0:5000'
    volumes:
      - './orderFlow:/app/orderFlow'  #doker will see changes automatically
    ports:
    - "5000:5000"
  app_test:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: pytest -v
    volumes:
      - './orderFlow:/app/orderFlow'  #doker will see changes automatically

