# Generated by Django 3.2.4 on 2021-06-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
