# Generated by Django 3.2.4 on 2021-06-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='details',
        ),
    ]
